try{foo()}catch(a){alert("Exception caught (foo not defined)")}alert(10);